FROM python:3.10-slim

EXPOSE 80

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN apt-get update && apt-get install -y python3-dev default-libmysqlclient-dev build-essential
RUN python -m pip install -r requirements.txt

WORKDIR /app
COPY ./app /app

CMD ["gunicorn", "-w", "2", "--bind", "0.0.0.0:80", "-k", "uvicorn.workers.UvicornWorker", "main:app"]
