version: '3.4'

services:
  magazine_mobile:
    image: magazine_mobile
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    environment:
      - database_username=u1346925_mobile
      - database_password=wO_2iI2pE9d!
      - database_ip=31.31.196.208
      - database_name=u1346925_mebel
      - mail_username=domaintestsmtp
      - mail_password=dN7Q4*WsZTG!RzU
      - mail_from=domaintestsmtp@rambler.ru
      - mail_port=465
      - mail_server=smtp.rambler.ru
