version: '3.4'

services:
  magazinemobile:
    image: magazinemobile
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
