version: '3.4'

services:
  web:
    image: magazine_mobile
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`<domain>`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
  
  traefik:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-certificates:/certificates"

volumes:
  traefik-certificates: